const teams = {
  'ARI': 'Arizona Cardinals',
  'CHI': 'Chicago Bears',
  'GB': 'Green Bay Packers',
  'NYG': 'New York Giants',
  'DET': 'Detroit Lions',
  'WSH': 'Washington Redskins',
  'PHI': 'Philadelphia Eagles',
  'PIT': 'Pittsburgh Steelers',
  'LAR': 'Los Angeles Rams',
  'SF': 'San Francisco 49ers',
  'CLE': 'Cleveland Browns',
  'IND': 'Indianapolis Colts',
  'DAL': 'Dallas Cowboys',
  'KC': 'Kansas City Chiefs',
  'LAC': 'Los Angeles Chargers',
  'DEN': 'Denver Broncos',
  'NYJ': 'New York Jets',
  'NE': 'New England Patriots',
  'OAK': 'Oakland Raiders',
  'TEN': 'Tennessee Titans',
  'BUF': 'Buffalo Bills',
  'MIN': 'Minnesota Vikings',
  'ATL': 'Atlanta Falcons',
  'MIA': 'Miami Dolphins',
  'NO': 'New Orleans Saints',
  'CIN': 'Cincinnati Bengals',
  'SEA': 'Seattle Seahawks',
  'TB': 'Tampa Bay Buccaneers',
  'CAR': 'Carolina Panthers',
  'JAX': 'Jacksonville Jaguars',
  'BAL': 'Baltimore Ravens',
  'HOU': 'Houston Texans'
};

export default teams;
